spring:
  application:
    name: desof
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/desof?&user=root&password=root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true

server:
  port: 8017
  servlet:
    session:
      cookie:
        http-only: true